
services:
  profiles-app:
    build: .
    container_name: profiles-app
    ports:
      - "3005:3005"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - profiles-network

  profiles-api:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: profiles-api
    ports:
      - "3001:3000"
    volumes:
      - ./data:/app/data
      - ./server.js:/app/server.js
    restart: unless-stopped
    networks:
      - profiles-network

networks:
  profiles-network:
    driver: bridge
